theme: minima
header_pages:
  - Organization/index.md
  - Credential/index.md
  - LearningProgram/index.md
author: Credential Engine
email: 'contact@credentialengine.org'
minima:
  social_links:
    - { platform: github, user_url: 'https://github.com/credentialengine' }
